name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test/requirements.txt
        pip install pytest
        pip install requests
        echo "${{ env.PYTHONPATH }}"
        echo "${{ env.PYTHONPATH }}" >> $GITHUB_PATH
    - name: Run pytest
      run: /path/to/pytest test/test_courses_pytest.py test/test_student_pytest.py test/test_university_pytest.py
